# Generated by Django 6.0.5 on 2026-06-17 05:55

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_knowledgechunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('platform_id', models.CharField(help_text='WhatsApp ID, IG SID, or FB PSID', max_length=255)),
                ('stage', models.CharField(choices=[('NEW', 'New Lead'), ('FOLLOWUP', 'Follow Up'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Closed Won'), ('LOST', 'Closed Lost')], default='NEW', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.client')),
            ],
            options={
                'unique_together': {('client', 'platform_id')},
            },
        ),
    ]
