# Generated by Django 6.0.5 on 2026-06-24 07:31

import api.models
import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.client_directory_path),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(default='en_US', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('components', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('audience_filter', models.CharField(default='ALL', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.client')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.template')),
            ],
        ),
    ]
