# Generated by Django 5.2.15 on 2026-06-24 10:27

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_phone_number_alter_knowledgedocument_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSession',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('current_node_id', models.CharField(max_length=255)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_sessions', to='api.client')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.workflow')),
            ],
        ),
    ]
