# Generated by Django 6.0.5 on 2026-06-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key'),
        ),
        migrations.AlterModelTable(
            name='session',
            table='django_session',
        ),
    ]
